version: '3'

services:
  tomcat:
    build:
      context: ./tomcat-container
      dockerfile: Dockerfile
    container_name: tomcat-csrf
    ports:
      - "8080:8080"

  csrf-server:
    build:
      context: ./csrf-attack-container
    container_name: csrf-server
    ports:
      - "5000:5000"
    depends_on:
      - tomcat
